# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: ./reactjs-org.sh
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: reactjs-org
          path: public
          warn: Output a warning but do not fail the action
          error: Fail the action with an error message
          ignore: Do not output any warnings or errors, the action does not fail
  
